# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\categoria_window__.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys

myDir = os.getcwd()
sys.path.append(myDir)
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage,QPixmap

import cv2
import imutils

from model.model import Model


m= Model()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 386)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 191, 16))
        self.label_2.setObjectName("label_2")
        self.inputext_nombrecategoria = QtWidgets.QLineEdit(self.centralwidget)
        self.inputext_nombrecategoria.setGeometry(QtCore.QRect(270, 80, 131, 20))
        self.inputext_nombrecategoria.setObjectName("inputext_nombrecategoria")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 330, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 160, 171, 151))
        self.label_3.setObjectName("label_3")
        self.btn_cargar_imagen_categoria = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cargar_imagen_categoria.setGeometry(QtCore.QRect(250, 120, 71, 23))
        self.btn_cargar_imagen_categoria.setObjectName("btn_cargar_imagen_categoria")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btncargarimagen = self.btn_cargar_imagen_categoria.clicked.connect(self.loadimagen)
    
    def loadimagen(self, hola):
        print("si sirve el boton")

          
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Crear Categoria"))
        self.label_2.setText(_translate("MainWindow", "Nombre de Categoria"))
        self.pushButton_2.setText(_translate("MainWindow", "Guardar"))
        self.label_3.setText(_translate("MainWindow", "Imagen Categoria"))
        self.btn_cargar_imagen_categoria.setText(_translate("MainWindow", "Cargar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
