# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregar_productos__.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.model import Model

import os
import sys
myDir = os.getcwd()
sys.path.append(myDir)
m= Model()
print("succes")

class Ui_VistaProducto(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 201)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 90, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 61, 16))
        self.label_5.setObjectName("label_5")
        self.input_nombre_producto = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nombre_producto.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.input_nombre_producto.setObjectName("input_nombre_producto")
        self.input_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.input_precio.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.input_precio.setObjectName("input_precio")
        self.input_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.input_marca.setGeometry(QtCore.QRect(100, 120, 113, 20))
        self.input_marca.setObjectName("input_marca")
        self.input_cantidad = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cantidad.setGeometry(QtCore.QRect(100, 150, 113, 20))
        self.input_cantidad.setObjectName("input_cantidad")
        self.button_guardar_producto = QtWidgets.QPushButton(self.centralwidget)
        self.button_guardar_producto.setGeometry(QtCore.QRect(250, 150, 131, 23))
        self.button_guardar_producto.setObjectName("button_guardar_producto")
        self.boxcomb_categoria = QtWidgets.QComboBox(self.centralwidget)
        self.boxcomb_categoria.setGeometry(QtCore.QRect(250, 40, 121, 22))
        self.boxcomb_categoria.setObjectName("boxcomb_categoria")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 20, 61, 16))
        self.label_6.setObjectName("label_6")
        self.idlabel = QtWidgets.QLabel(self.centralwidget)
        self.idlabel.setGeometry(QtCore.QRect(330, 20, 61, 16))
        self.idlabel.setObjectName("idlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.botonguardar = self.button_guardar_producto.clicked.connect(self.datos_tabla_productos)
        self.loadpleas =self.cargarmicombo()
        self.comb = self.boxcomb_categoria.activated.connect(self.do_something)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Crear Producto"))
        self.label_2.setText(_translate("MainWindow", "Producto"))
        self.label_3.setText(_translate("MainWindow", "Marca"))
        self.label_4.setText(_translate("MainWindow", "Precio"))
        self.label_5.setText(_translate("MainWindow", "cantidad"))
        self.button_guardar_producto.setText(_translate("MainWindow", "Guardar"))
        self.label_6.setText(_translate("MainWindow", "categoria"))
        self.idlabel.setText(_translate("MainWindow", "id"))
        
        
    def do_something(self,):
        self.getnamecategoria = str(self.boxcomb_categoria.currentText())
        self.returnidcategoria = m.buscar_id_categorias(self.getnamecategoria)
        self.idlabel.setText(str(self.returnidcategoria))

    def datos_tabla_productos(self,):
        self.idcategoria = self.idlabel.text()
        self.nombre_producto = self.input_nombre_producto.text()
        self.precio_producto = float(self.input_precio.text())
        self.marca_producto = self.input_marca.text()
        self.cantidad_producto = self.input_cantidad.text() 

        m.create_productos(self.idcategoria,self.nombre_producto,self.precio_producto,self.marca_producto,self.cantidad_producto)
        print(self.idcategoria,self.nombre_producto,self.precio_producto,self.marca_producto,self.cantidad_producto)
        


    def cargarmicombo(self,):
        self.combo = self.boxcomb_categoria
        self.model = m.mostrarcaetgorias()      
        self.combo.addItems(self.model)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_VistaProducto()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
