# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregar_empleado.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.model import Model

import os
import sys
myDir = os.getcwd()
sys.path.append(myDir)
m= Model()
print("succes")

class Ui_VistaEmpleado(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 404)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 290, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 190, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 190, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 190, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 80, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 80, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(580, 80, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(590, 190, 71, 16))
        self.label_10.setObjectName("label_10")
        self.input_clientename = QtWidgets.QLineEdit(self.centralwidget)
        self.input_clientename.setGeometry(QtCore.QRect(220, 130, 141, 20))
        self.input_clientename.setObjectName("input_clientename")
        self.boxcmb_tipo_empleado = QtWidgets.QComboBox(self.centralwidget)
        self.boxcmb_tipo_empleado.setGeometry(QtCore.QRect(60, 130, 131, 22))
        self.boxcmb_tipo_empleado.setObjectName("boxcmb_tipo_empleado")
        self.boxcmb_tipo_empleado.addItem("")
        self.boxcmb_tipo_empleado.addItem("")
        self.input_clientelastname = QtWidgets.QLineEdit(self.centralwidget)
        self.input_clientelastname.setGeometry(QtCore.QRect(400, 130, 141, 20))
        self.input_clientelastname.setObjectName("input_clientelastname")
        self.input_contrasea = QtWidgets.QLineEdit(self.centralwidget)
        self.input_contrasea.setGeometry(QtCore.QRect(580, 130, 141, 20))
        self.input_contrasea.setObjectName("input_contrasea")
        self.input_dni = QtWidgets.QLineEdit(self.centralwidget)
        self.input_dni.setGeometry(QtCore.QRect(230, 230, 141, 20))
        self.input_dni.setObjectName("input_dni")
        self.input_correo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_correo.setGeometry(QtCore.QRect(410, 230, 141, 20))
        self.input_correo.setObjectName("input_correo")
        self.input_direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.input_direccion.setGeometry(QtCore.QRect(590, 230, 141, 20))
        self.input_direccion.setObjectName("input_direccion")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(240, 290, 101, 16))
        self.label_11.setObjectName("label_11")
        self.input_celular = QtWidgets.QLineEdit(self.centralwidget)
        self.input_celular.setGeometry(QtCore.QRect(60, 330, 141, 20))
        self.input_celular.setObjectName("input_celular")
        self.input_fecha_nacimiento = QtWidgets.QDateEdit(self.centralwidget)
        self.input_fecha_nacimiento.setGeometry(QtCore.QRect(240, 330, 110, 22))
        self.input_fecha_nacimiento.setObjectName("input_fecha_nacimiento")
        self.btn_guardarusuario = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardarusuario.setGeometry(QtCore.QRect(610, 300, 75, 23))
        self.btn_guardarusuario.setObjectName("btn_guardarusuario")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(610, 340, 75, 23))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.boxcmb_sexo = QtWidgets.QComboBox(self.centralwidget)
        self.boxcmb_sexo.setGeometry(QtCore.QRect(60, 230, 131, 22))
        self.boxcmb_sexo.setObjectName("boxcmb_sexo")
        self.boxcmb_sexo.addItem("")
        self.boxcmb_sexo.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.crearempleado = self.btn_guardarusuario.clicked.connect(self.guardarusuariofunc)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Crear Usuario"))
        self.label_2.setText(_translate("MainWindow", "Tipo usuario"))
        self.label_3.setText(_translate("MainWindow", "Celular"))
        self.label_4.setText(_translate("MainWindow", "DNI"))
        self.label_5.setText(_translate("MainWindow", "Correo Electronico"))
        self.label_6.setText(_translate("MainWindow", "Sexo"))
        self.label_7.setText(_translate("MainWindow", "Nombres"))
        self.label_8.setText(_translate("MainWindow", "Apellidos"))
        self.label_9.setText(_translate("MainWindow", "Constraseña"))
        self.label_10.setText(_translate("MainWindow", "Direccion"))
        self.boxcmb_tipo_empleado.setItemText(0, _translate("MainWindow", "Empleado"))
        self.boxcmb_tipo_empleado.setItemText(1, _translate("MainWindow", "Encargado"))
        self.label_11.setText(_translate("MainWindow", "Fecha de Nacimiento"))
        self.btn_guardarusuario.setText(_translate("MainWindow", "Crear Usuario"))
        self.btn_cerrar.setText(_translate("MainWindow", "Cerrar"))
        self.boxcmb_sexo.setItemText(0, _translate("MainWindow", "M"))
        self.boxcmb_sexo.setItemText(1, _translate("MainWindow", "F"))

    def guardarusuariofunc(self,):
        A = self.boxcmb_tipo_empleado.currentText()
        self.getnameusuario = self.input_clientename.text()
        self.getlastnameusuario = self.input_clientelastname.text()
        self.getcontrasena = self.input_contrasea.text()
        self.getcmbsexo = self.boxcmb_sexo.currentText()
        self.getdni = self.input_dni.text()
        self.getcorreo = self.input_correo.text()
        self.getdireccion = self.input_direccion.text()
        self.getcelular = self.input_celular.text()
        self.getfecha_nacimiento =self.input_fecha_nacimiento.date().toPyDate()
        print(self.getnameusuario,self.getlastnameusuario,self.getdni,self.getfecha_nacimiento,self.getcmbsexo,self.getdireccion,self.getcelular,self.getcmbusuario,self.getcorreo,self.getcontrasena)
        m.crear_encargado(self.getnameusuario,self.getlastnameusuario,self.getdni,self.getfecha_nacimiento,self.getcmbsexo,self.getdireccion,self.getcelular,self.getcmbusuario,self.getcorreo,self.getcontrasena)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_VistaEmpleado()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
