# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_window__.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from model.model import Model    
from menu_principal_venta___ import Ui_Menu_venta_principal_
import os
import sys
myDir = os.getcwd()
sys.path.append(myDir)
m= Model()
print("succes")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 100, 251, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 160, 251, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 50, 71, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.butonlogin = self.pushButton.clicked.connect(self.funcionlogin)

    def funcionlogin(self,):
        self.getinputcorreo = self.lineEdit.text()
        self.getinputcontrasena = self.lineEdit_2.text()

        self.executebuton = m.login_empleado(self.getinputcorreo,self.getinputcontrasena)
        print(self.executebuton)
        if self.executebuton:
            self.ventana=QtWidgets.QMainWindow()
            self.ui=Ui_Menu_venta_principal_()
            self.ui.setupUi(self.ventana)
            self.ventana.show()
           



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "contraseña"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar Sesion"))
        self.label.setText(_translate("MainWindow", "Inicia Sesion"))
        self.label_2.setText(_translate("MainWindow", "imagen"))
        self.label_3.setText(_translate("MainWindow", "Bienvenido"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "contraseña"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar Sesion"))
        self.label.setText(_translate("MainWindow", "Inicia Sesion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
