# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu_principal_venta___.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.model import Model
from PyQt5.QtWidgets import QApplication, QWidget, QListWidget, QVBoxLayout, QListWidgetItem ,QMessageBox
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QPushButton
from agregar_productos__ import Ui_VistaProducto
from categoria_window__ import Ui_VistaCategoria
from agregar_empleado import Ui_VistaEmpleado
import json

import os
import sys
myDir = os.getcwd()
sys.path.append(myDir)
m= Model()
print("succes")

encargadoid = "e8208242-7887-11ed-9935-001a7dda7113"

class Ui_Menu_venta_principal_(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 701))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 40, 151, 20))
        self.label.setObjectName("label")
        self.input_find = QtWidgets.QLineEdit(self.tab)
        self.input_find.setGeometry(QtCore.QRect(20, 60, 151, 20))
        self.input_find.setObjectName("input_find")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(320, 140, 141, 16))
        self.label_3.setObjectName("label_3")
        self.input_producto_name = QtWidgets.QLineEdit(self.tab)
        self.input_producto_name.setGeometry(QtCore.QRect(320, 110, 261, 20))
        self.input_producto_name.setObjectName("input_producto_name")
        self.input_categoria_name = QtWidgets.QLineEdit(self.tab)
        self.input_categoria_name.setGeometry(QtCore.QRect(320, 160, 121, 20))
        self.input_categoria_name.setObjectName("input_categoria_name")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(320, 190, 121, 16))
        self.label_4.setObjectName("label_4")
        self.input_cantidad = QtWidgets.QLineEdit(self.tab)
        self.input_cantidad.setGeometry(QtCore.QRect(320, 210, 121, 20))
        self.input_cantidad.setObjectName("input_cantidad")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(470, 140, 121, 16))
        self.label_5.setObjectName("label_5")
        self.input_precio = QtWidgets.QLineEdit(self.tab)
        self.input_precio.setGeometry(QtCore.QRect(470, 160, 121, 20))
        self.input_precio.setObjectName("input_precio")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(480, 190, 31, 16))
        self.label_6.setObjectName("label_6")
        self.input_total = QtWidgets.QLineEdit(self.tab)
        self.input_total.setGeometry(QtCore.QRect(470, 210, 121, 20))
        self.input_total.setObjectName("input_total")
        self.btn_agregar = QtWidgets.QPushButton(self.tab)
        self.btn_agregar.setGeometry(QtCore.QRect(320, 240, 271, 41))
        self.btn_agregar.setCheckable(False)
        self.btn_agregar.setAutoDefault(False)
        self.btn_agregar.setDefault(False)
        self.btn_agregar.setFlat(False)
        self.btn_agregar.setObjectName("btn_agregar")
        self.list_productos = QtWidgets.QListWidget(self.tab)
        self.list_productos.setGeometry(QtCore.QRect(20, 120, 251, 161))
        self.list_productos.setObjectName("list_productos")
        self.tabl_widget_productos = QtWidgets.QTableWidget(self.tab)
        self.tabl_widget_productos.setGeometry(QtCore.QRect(20, 330, 581, 321))
        self.tabl_widget_productos.setObjectName("tabl_widget_productos")
        self.tabl_widget_productos.setColumnCount(0)
        self.tabl_widget_productos.setRowCount(0)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(660, 40, 61, 16))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(30, 280, 891, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(660, 120, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(660, 150, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(660, 180, 41, 16))
        self.label_11.setObjectName("label_11")
        self.input_dni = QtWidgets.QLineEdit(self.tab)
        self.input_dni.setGeometry(QtCore.QRect(720, 120, 191, 20))
        self.input_dni.setObjectName("input_dni")
        self.input_nombre_cliente = QtWidgets.QLineEdit(self.tab)
        self.input_nombre_cliente.setGeometry(QtCore.QRect(720, 150, 191, 20))
        self.input_nombre_cliente.setObjectName("input_nombre_cliente")
        self.input_apellido = QtWidgets.QLineEdit(self.tab)
        self.input_apellido.setGeometry(QtCore.QRect(720, 180, 191, 20))
        self.input_apellido.setObjectName("input_apellido")
        self.btn_buscar_dni = QtWidgets.QPushButton(self.tab)
        self.btn_buscar_dni.setGeometry(QtCore.QRect(840, 50, 75, 23))
        self.btn_buscar_dni.setObjectName("btn_buscar_dni")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(660, 210, 41, 16))
        self.label_12.setObjectName("label_12")
        self.input_correo = QtWidgets.QLineEdit(self.tab)
        self.input_correo.setGeometry(QtCore.QRect(720, 210, 191, 20))
        self.input_correo.setObjectName("input_correo")
        self.chbox_enviarcorreo = QtWidgets.QCheckBox(self.tab)
        self.chbox_enviarcorreo.setGeometry(QtCore.QRect(770, 260, 141, 17))
        self.chbox_enviarcorreo.setObjectName("chbox_enviarcorreo")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 300, 141, 16))
        self.label_13.setObjectName("label_13")
        self.input_subtotal = QtWidgets.QLineEdit(self.tab)
        self.input_subtotal.setGeometry(QtCore.QRect(750, 380, 121, 20))
        self.input_subtotal.setText("")
        self.input_subtotal.setObjectName("input_subtotal")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(670, 380, 61, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(670, 430, 61, 20))
        self.label_15.setObjectName("label_15")
        self.input_iva = QtWidgets.QLineEdit(self.tab)
        self.input_iva.setGeometry(QtCore.QRect(750, 430, 121, 20))
        self.input_iva.setText("")
        self.input_iva.setObjectName("input_iva")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(670, 480, 61, 20))
        self.label_16.setObjectName("label_16")
        self.input_total_2 = QtWidgets.QLineEdit(self.tab)
        self.input_total_2.setGeometry(QtCore.QRect(750, 480, 121, 20))
        self.input_total_2.setText("")
        self.input_total_2.setObjectName("input_total_2")
        self.btn_completar_compra = QtWidgets.QPushButton(self.tab)
        self.btn_completar_compra.setGeometry(QtCore.QRect(680, 530, 191, 41))
        self.btn_completar_compra.setObjectName("btn_completar_compra")
        self.btn_lista_productos = QtWidgets.QPushButton(self.tab)
        self.btn_lista_productos.setGeometry(QtCore.QRect(180, 60, 75, 23))
        self.btn_lista_productos.setObjectName("btn_lista_productos")
        self.btn_limpiar_lista = QtWidgets.QPushButton(self.tab)
        self.btn_limpiar_lista.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.btn_limpiar_lista.setObjectName("btn_limpiar_lista")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(280, 40, 20, 241))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(620, 40, 20, 241))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(620, 300, 20, 351))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(320, 40, 141, 16))
        self.label_7.setObjectName("label_7")
        self.lbl_forid = QtWidgets.QLabel(self.tab)
        self.lbl_forid.setGeometry(QtCore.QRect(320, 60, 271, 16))
        self.lbl_forid.setText("")
        self.lbl_forid.setObjectName("lbl_forid")
        self.btn_limpiar_tabla = QtWidgets.QPushButton(self.tab)
        self.btn_limpiar_tabla.setGeometry(QtCore.QRect(520, 300, 75, 23))
        self.btn_limpiar_tabla.setObjectName("btn_limpiar_tabla")
        self.btn_borrar_item = QtWidgets.QPushButton(self.tab)
        self.btn_borrar_item.setGeometry(QtCore.QRect(440, 300, 75, 23))
        self.btn_borrar_item.setObjectName("btn_borrar_item")
        self.btn_guardar_cliente = QtWidgets.QPushButton(self.tab)
        self.btn_guardar_cliente.setGeometry(QtCore.QRect(760, 50, 75, 23))
        self.btn_guardar_cliente.setObjectName("btn_guardar_cliente")
        self.btn_calcular_lprecio = QtWidgets.QPushButton(self.tab)
        self.btn_calcular_lprecio.setGeometry(QtCore.QRect(800, 330, 75, 23))
        self.btn_calcular_lprecio.setObjectName("btn_calcular_lprecio")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(660, 90, 31, 16))
        self.label_17.setObjectName("label_17")
        self.lbl_idclinete__ = QtWidgets.QLabel(self.tab)
        self.lbl_idclinete__.setGeometry(QtCore.QRect(720, 90, 191, 20))
        self.lbl_idclinete__.setText("")
        self.lbl_idclinete__.setObjectName("lbl_idclinete__")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(10, 20, 891, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 61, 20))
        self.label_18.setObjectName("label_18")
        self.lbl_nombre_empleado = QtWidgets.QLabel(self.tab)
        self.lbl_nombre_empleado.setGeometry(QtCore.QRect(90, 10, 131, 20))
        self.lbl_nombre_empleado.setText("")
        self.lbl_nombre_empleado.setObjectName("lbl_nombre_empleado")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(590, 10, 21, 16))
        self.label_20.setObjectName("label_20")
        self.lblid_empleado = QtWidgets.QLabel(self.tab)
        self.lblid_empleado.setGeometry(QtCore.QRect(610, 10, 291, 20))
        self.lblid_empleado.setText("")
        self.lblid_empleado.setObjectName("lblid_empleado")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(290, 10, 71, 20))
        self.label_21.setObjectName("label_21")
        self.lbltipoempleado = QtWidgets.QLabel(self.tab)
        self.lbltipoempleado.setGeometry(QtCore.QRect(370, 10, 131, 20))
        self.lbltipoempleado.setText("")
        self.lbltipoempleado.setObjectName("lbltipoempleado")
        self.tabWidget.addTab(self.tab, "")
        self.tab_56 = QtWidgets.QWidget()
        self.tab_56.setObjectName("tab_56")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_56)
        self.tableWidget_4.setGeometry(QtCore.QRect(50, 130, 671, 501))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_56)
        self.lineEdit_43.setGeometry(QtCore.QRect(50, 90, 251, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_56)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 90, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_53 = QtWidgets.QLabel(self.tab_56)
        self.label_53.setGeometry(QtCore.QRect(50, 60, 81, 16))
        self.label_53.setObjectName("label_53")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_56)
        self.pushButton_10.setGeometry(QtCore.QRect(760, 60, 121, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_56)
        self.pushButton_11.setGeometry(QtCore.QRect(760, 100, 121, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_56)
        self.pushButton_12.setGeometry(QtCore.QRect(770, 640, 121, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.cmboxcategoria_productos = QtWidgets.QComboBox(self.tab_56)
        self.cmboxcategoria_productos.setGeometry(QtCore.QRect(580, 90, 131, 22))
        self.cmboxcategoria_productos.setObjectName("cmboxcategoria_productos")
        self.cmboxcategoria_productos.addItem("")
        self.cmboxcategoria_productos.addItem("")
        self.lblid_empleado_2 = QtWidgets.QLabel(self.tab_56)
        self.lblid_empleado_2.setGeometry(QtCore.QRect(600, 10, 291, 20))
        self.lblid_empleado_2.setText("")
        self.lblid_empleado_2.setObjectName("lblid_empleado_2")
        self.label_22 = QtWidgets.QLabel(self.tab_56)
        self.label_22.setGeometry(QtCore.QRect(580, 10, 21, 16))
        self.label_22.setObjectName("label_22")
        self.lbl_nombre_empleado_2 = QtWidgets.QLabel(self.tab_56)
        self.lbl_nombre_empleado_2.setGeometry(QtCore.QRect(80, 10, 131, 20))
        self.lbl_nombre_empleado_2.setText("")
        self.lbl_nombre_empleado_2.setObjectName("lbl_nombre_empleado_2")
        self.lbltipoempleado_2 = QtWidgets.QLabel(self.tab_56)
        self.lbltipoempleado_2.setGeometry(QtCore.QRect(360, 10, 131, 20))
        self.lbltipoempleado_2.setText("")
        self.lbltipoempleado_2.setObjectName("lbltipoempleado_2")
        self.label_23 = QtWidgets.QLabel(self.tab_56)
        self.label_23.setGeometry(QtCore.QRect(280, 10, 71, 20))
        self.label_23.setObjectName("label_23")
        self.label_19 = QtWidgets.QLabel(self.tab_56)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.label_19.setObjectName("label_19")
        self.line_3 = QtWidgets.QFrame(self.tab_56)
        self.line_3.setGeometry(QtCore.QRect(0, 20, 891, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab_56, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setGeometry(QtCore.QRect(30, 50, 61, 16))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_2)
        self.label_55.setGeometry(QtCore.QRect(30, 420, 61, 16))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_2)
        self.label_56.setGeometry(QtCore.QRect(30, 100, 61, 16))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(30, 300, 61, 16))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(30, 180, 61, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_2)
        self.label_60.setGeometry(QtCore.QRect(30, 140, 61, 16))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(30, 260, 61, 16))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setGeometry(QtCore.QRect(30, 220, 61, 16))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setGeometry(QtCore.QRect(30, 380, 61, 16))
        self.label_63.setObjectName("label_63")
        self.input_cargo_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_cargo_empleado.setGeometry(QtCore.QRect(90, 420, 181, 20))
        self.input_cargo_empleado.setObjectName("input_cargo_empleado")
        self.input_nombre_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_nombre_empleado.setGeometry(QtCore.QRect(90, 100, 181, 20))
        self.input_nombre_empleado.setObjectName("input_nombre_empleado")
        self.input_apellido_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_apellido_empleado.setGeometry(QtCore.QRect(90, 140, 181, 20))
        self.input_apellido_empleado.setObjectName("input_apellido_empleado")
        self.input_edad_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_edad_empleado.setGeometry(QtCore.QRect(90, 180, 181, 20))
        self.input_edad_empleado.setObjectName("input_edad_empleado")
        self.input_sexo_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_sexo_empleado.setGeometry(QtCore.QRect(90, 220, 181, 20))
        self.input_sexo_empleado.setObjectName("input_sexo_empleado")
        self.input_dni_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_dni_empleado.setGeometry(QtCore.QRect(90, 260, 181, 20))
        self.input_dni_empleado.setObjectName("input_dni_empleado")
        self.input_ccelular_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_ccelular_empleado.setGeometry(QtCore.QRect(90, 300, 181, 20))
        self.input_ccelular_empleado.setObjectName("input_ccelular_empleado")
        self.input_correo_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_correo_empleado.setGeometry(QtCore.QRect(90, 340, 181, 20))
        self.input_correo_empleado.setObjectName("input_correo_empleado")
        self.input_direccion_empleado = QtWidgets.QLineEdit(self.tab_2)
        self.input_direccion_empleado.setGeometry(QtCore.QRect(90, 380, 181, 20))
        self.input_direccion_empleado.setObjectName("input_direccion_empleado")
        self.line_13 = QtWidgets.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(370, 40, 16, 571))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.tablewid_empleados = QtWidgets.QTableWidget(self.tab_2)
        self.tablewid_empleados.setGeometry(QtCore.QRect(420, 100, 481, 381))
        self.tablewid_empleados.setObjectName("tablewid_empleados")
        self.tablewid_empleados.setColumnCount(0)
        self.tablewid_empleados.setRowCount(0)
        self.btn_actualizar_empleado = QtWidgets.QPushButton(self.tab_2)
        self.btn_actualizar_empleado.setGeometry(QtCore.QRect(290, 60, 75, 23))
        self.btn_actualizar_empleado.setObjectName("btn_actualizar_empleado")
        self.label_93 = QtWidgets.QLabel(self.tab_2)
        self.label_93.setGeometry(QtCore.QRect(420, 60, 91, 16))
        self.label_93.setObjectName("label_93")
        self.btn_actualizar_empleado_2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_actualizar_empleado_2.setGeometry(QtCore.QRect(200, 60, 75, 23))
        self.btn_actualizar_empleado_2.setObjectName("btn_actualizar_empleado_2")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(20, 20, 891, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(30, 10, 61, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(300, 10, 71, 20))
        self.label_25.setObjectName("label_25")
        self.lbltipoempleado_3 = QtWidgets.QLabel(self.tab_2)
        self.lbltipoempleado_3.setGeometry(QtCore.QRect(380, 10, 131, 20))
        self.lbltipoempleado_3.setText("")
        self.lbltipoempleado_3.setObjectName("lbltipoempleado_3")
        self.lblid_empleado_3 = QtWidgets.QLabel(self.tab_2)
        self.lblid_empleado_3.setGeometry(QtCore.QRect(620, 10, 291, 20))
        self.lblid_empleado_3.setText("")
        self.lblid_empleado_3.setObjectName("lblid_empleado_3")
        self.lbl_nombre_empleado_3 = QtWidgets.QLabel(self.tab_2)
        self.lbl_nombre_empleado_3.setGeometry(QtCore.QRect(100, 10, 131, 20))
        self.lbl_nombre_empleado_3.setText("")
        self.lbl_nombre_empleado_3.setObjectName("lbl_nombre_empleado_3")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(600, 10, 21, 16))
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_55 = QtWidgets.QWidget()
        self.tab_55.setObjectName("tab_55")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_55)
        self.tableWidget.setGeometry(QtCore.QRect(390, 80, 501, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.tab_55)
        self.pushButton.setGeometry(QtCore.QRect(40, 460, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_55)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 460, 121, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_55)
        self.checkBox.setGeometry(QtCore.QRect(40, 390, 251, 21))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_55)
        self.lineEdit.setGeometry(QtCore.QRect(40, 420, 271, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.line_5 = QtWidgets.QFrame(self.tab_55)
        self.line_5.setGeometry(QtCore.QRect(10, 20, 891, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_27 = QtWidgets.QLabel(self.tab_55)
        self.label_27.setGeometry(QtCore.QRect(20, 10, 61, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_55)
        self.label_28.setGeometry(QtCore.QRect(290, 10, 71, 20))
        self.label_28.setObjectName("label_28")
        self.lbltipoempleado_4 = QtWidgets.QLabel(self.tab_55)
        self.lbltipoempleado_4.setGeometry(QtCore.QRect(370, 10, 131, 20))
        self.lbltipoempleado_4.setText("")
        self.lbltipoempleado_4.setObjectName("lbltipoempleado_4")
        self.lblid_empleado_4 = QtWidgets.QLabel(self.tab_55)
        self.lblid_empleado_4.setGeometry(QtCore.QRect(610, 10, 291, 20))
        self.lblid_empleado_4.setText("")
        self.lblid_empleado_4.setObjectName("lblid_empleado_4")
        self.lbl_nombre_empleado_4 = QtWidgets.QLabel(self.tab_55)
        self.lbl_nombre_empleado_4.setGeometry(QtCore.QRect(90, 10, 131, 20))
        self.lbl_nombre_empleado_4.setText("")
        self.lbl_nombre_empleado_4.setObjectName("lbl_nombre_empleado_4")
        self.label_29 = QtWidgets.QLabel(self.tab_55)
        self.label_29.setGeometry(QtCore.QRect(590, 10, 21, 16))
        self.label_29.setObjectName("label_29")
        self.tabWidget.addTab(self.tab_55, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#Ventana menu_principal
####################################################################################################
        #botonesfactura
        self.botoncalcular_datos = self.btn_calcular_lprecio.clicked.connect(self.calcularprecios)
        self.crearfactura = self.btn_completar_compra.clicked.connect(self.conpletar_venta)
        #funcion de lista
        self.accionbuscar_nombre = self.btn_lista_productos.clicked.connect(self.buscar_por_nombre)
        self.choose_product = self.list_productos.currentItemChanged.connect(self.putdatainview)
        self.botondrop = self.btn_limpiar_lista.clicked.connect(self.dropdata)
        #bototnes_tabla
        self.bonton_agregar_tabla = self.btn_agregar.clicked.connect(self.agruegar_datostabla)
        self.boton_limpiar_tabla = self.btn_limpiar_tabla.clicked.connect(self.borrar_todalatabla)
        self.boton_limpiar_todad_tabla = self.btn_borrar_item.clicked.connect(self.limpiar)
        #botonesdni
        self.botondni = self.btn_buscar_dni.clicked.connect(self.checkdni)
        self.botonguardarcliente = self.btn_guardar_cliente.clicked.connect(self.guardar_cliente)
        #columnas
        self.tabl_widget_productos.setColumnCount(5)
        self.arraheader = ["id","producto","cantidad","precio","total"]
        self.tabl_widget_productos.setHorizontalHeaderLabels(self.arraheader)   
        #self.cambio_input =self.input_cantidad.textChanged.connect(self.dooperation)
####################################################################################################

##################################################################################################
        
#ventana editar Productos
        self.tableWidget_4.setColumnCount(5)
        self.arraheader = ["id","producto","precio","marca","cantidad"]
        self.tableWidget_4.setHorizontalHeaderLabels(self.arraheader) 

        self.btnlistar = self.pushButton_12.clicked.connect(self.listaproductotabla)

        self.tableWidget.setColumnCount(4)
        self.arraheader = ["id","forma de pago","IGV","Monto"]
        self.tableWidget.setHorizontalHeaderLabels(self.arraheader)

        self.btnlistarfacturas = self.pushButton_2.clicked.connect(self.listafacturastabla)

        self.tablewid_empleados.setColumnCount(6)
        self.arraheader = ["id","nombre","apellido","sexo","tipo de empleado"]
        self.tablewid_empleados.setHorizontalHeaderLabels(self.arraheader)

        self.btnlistausuarios = self.btn_actualizar_empleado.clicked.connect(self.listaempleadotabla)


        self.openviewempleado = self.btn_actualizar_empleado_2.clicked.connect(self.openwindowempleado)
        self.openviewproductos = self.pushButton_10.clicked.connect(self.openwindowproducto)
        self.openviewcategoria = self.pushButton_11.clicked.connect(self.openwindowcategoria)
#funciones


    def listaempleadotabla(self,):
        self.table = self.tablewid_empleados
        self.products = m.obtener_todo_empleado()
        self.table.setRowCount(0)
        for row_number,row_data in enumerate(self.products):
            self.table.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.table.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def listafacturastabla(self,):
        self.table = self.tableWidget
        self.products = m.obtener_todo_factura()
        self.table.setRowCount(0)
        for row_number,row_data in enumerate(self.products):
            self.table.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.table.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def listaproductotabla(self,):
        self.table = self.tableWidget_4
        self.products = m.obtener_todo_producto()
        self.table.setRowCount(0)
        for row_number,row_data in enumerate(self.products):
            self.table.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.table.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
                
    def openwindowproducto(self,):       
        self.ventana=QtWidgets.QMainWindow()
        self.ui=Ui_VistaProducto()
        self.ui.setupUi(self.ventana)
        self.ventana.show()

    def openwindowcategoria(self):  
        self.ventana=QtWidgets.QMainWindow()
        self.ui=Ui_VistaCategoria()
        self.ui.setupUi(self.ventana)
        self.ventana.show()

    def openwindowempleado(self):
        self.ventana=QtWidgets.QMainWindow()
        self.ui=Ui_VistaEmpleado()
        self.ui.setupUi(self.ventana)
        self.ventana.show()

##################################################################################################



 #Ventana menu_principal 
 #############################################################################################################      
    def conpletar_venta(self,):
        self.getlabelidcliente = self.lbl_idclinete__.text()
        self.getmontototal = self.input_total_2.text()
        self.getigvtotal = self.input_iva.text()

        self.crearnewfactura = m.crear_factura(self.getigvtotal,self.getmontototal,self.getlabelidcliente,encargadoid)

        if self.crearnewfactura :
            self.valoresdetalles =self.getdataforcreatedetallesfactura()
            self.getidproducto = ""
            self.getmondelproducto = 0.0
            self.getcantidadproducto = 0.0
            self.getprecioproducto = 0.0

            for x in self.valoresdetalles:
                self.getidproducto = x[0]
                self.getmondelproducto = x[4]
                self.getcantidadproducto = x[2]
                self.getprecioproducto = x[3]
                m.crear_detalle_factura(self.getprecioproducto,self.getcantidadproducto,self.getmondelproducto,self.getidproducto,self.crearnewfactura)

    def getdataforcreatedetallesfactura(self,):
        self.getrows = self.tabl_widget_productos.rowCount()
        items = []
        for n in range(self.getrows):
            fila=[]
            for column in range(9):
                thing = self.tabl_widget_productos.item(n,column)
                if thing is not None and thing.text() != "":
                   fila.append(thing.text())
                   print(fila)
            items.append((fila))
            print(len(items))
            print(fila,">>>")
            print(items,"<<<<<items>>>")   
        return items 

    def calcularprecios(self,):
        self.getrows = self.tabl_widget_productos.rowCount()
        items = []
        for n in range(self.getrows):
            fila=[]
            for column in range(9):
                thing = self.tabl_widget_productos.item(n,column)
                if thing is not None and thing.text() != "":
                   fila.append(thing.text())
                   print(fila)
            items.append(float(fila[4]))
            print(fila,">>>")
            print(items,"<<<<<items>>>")

        result = 0.0
        for c in items:
            result += c

        if result != 0.0:
            self.iva = round((result * 0.18),2)
            self.subtotal = round((result - self.iva),2)
            self.input_subtotal.setText(str(self.subtotal))
            self.input_iva.setText(str(self.iva)) 
            self.input_total_2.setText(str(result))

    def limpiar(self,):
        self.tablita = self.tabl_widget_productos
        rows =self.tablita.selectionModel().selectedRows()
        for r in rows:
            self.tablita.removeRow(r.row())

        #self.tabl_widget_productos.setRowCount(0) borrar toda la tabla
    def funciondepopup(self,titulo,texto):
        ret = QMessageBox()
        ret.setWindowTitle(titulo)
        ret.setText(texto)
        ret.setIcon(QMessageBox.Question)
        ret.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)
        ret.setDefaultButton(QMessageBox.Ok)
        self.x = ret.exec_()
        return self.x

    def guardar_cliente(self,):
        self.get_dnitext = self.input_dni.text()
        self.get_nombreclitext = self.input_nombre_cliente.text() 
        self.get_apellidotext = self.input_apellido.text()
    
        self.dni_creado = m.crear_cliente(self.get_nombreclitext, self.get_apellidotext, self.get_dnitext)

        if self.dni_creado:
            self.funciondepopup("CLIENTE REGISTRADO","Cliente Guardado correctamente")
            self.check_dni_database = m.buscar_dni(self.get_dnitext)
            print((self.check_dni_database[0]),"guardar y mostrar en lbl dni")
            self.lbl_idclinete__.setText(self.check_dni_database[0])
                        
    def checkdni(self,):
        self.get_dnitext = self.input_dni.text()
        self.get_nombreclitext = self.input_nombre_cliente.text() 
        self.get_apellidotext = self.input_apellido.text()

        self.check_dni_database = m.buscar_dni(self.get_dnitext)

        if self.check_dni_database:
            self.lbl_idclinete__.setText(self.check_dni_database[0])
            self.input_nombre_cliente.setText(self.check_dni_database[1])
            self.input_apellido.setText(self.check_dni_database[2])
            print("dni si exite")
            print(self.check_dni_database)           
        else:    
            self.valuepopoup =self.funciondepopup("DNI NO REGISTRADO","¿Desea añadir  un cliente nuevo?")
            if self.valuepopoup == QMessageBox.Ok:
                self.checkout = m.consultadniapi(self.get_dnitext)
                if self.checkout:
                    nombres = json.dumps(self.checkout["nombres"])
                    nombre_newstring=nombres.strip('"')
                    self.input_nombre_cliente.setText(nombre_newstring)
                    ape_paterno = json.dumps(self.checkout["apellidoPaterno"])
                    ape_materno = json.dumps(self.checkout["apellidoMaterno"])
                    apepaterno_newstring=ape_paterno.strip('"')
                    apematerno_newstring=ape_materno.strip('"')
                    apellido_completo = apepaterno_newstring + " "  +apematerno_newstring
                    self.input_apellido.setText(apellido_completo)
                    """if self.input_dni.text() and len(self.input_nombre_cliente.text())>0:
                        self.dni_creado = m.crear_cliente(self.get_nombreclitext, self.get_apellidotext, self.get_dnitext)
                        if(self.dni_creado):
                            print("usuario creado revisa la db")"""
                    
    def agruegar_datostabla(self,):
        self.parse_precio = self.input_precio.text()
        self.result = float(self.parse_precio)
        self.parse_cantidad = self.input_cantidad.text()
        self.result2 = float(self.parse_cantidad)
        self.result3 = round((self.result * self.result2), 2)
        self.result4 = str(self.result3)

        self.rowposition = self.tabl_widget_productos.rowCount()
        self.tabl_widget_productos.insertRow(self.rowposition)
        self.tabl_widget_productos.setItem(self.rowposition,0,QtWidgets.QTableWidgetItem(self.lbl_forid.text()))
        self.tabl_widget_productos.setItem(self.rowposition,1,QtWidgets.QTableWidgetItem(self.input_producto_name.text()))
        self.tabl_widget_productos.setItem(self.rowposition,2,QtWidgets.QTableWidgetItem(self.input_cantidad.text()))
        self.tabl_widget_productos.setItem(self.rowposition,3,QtWidgets.QTableWidgetItem(self.input_precio.text()))
        self.tabl_widget_productos.setItem(self.rowposition,4,QtWidgets.QTableWidgetItem(self.result4))

    def putdatainview(self,):
        self.getname_fromlist = self.list_productos.currentItem().text()
        self.valor_elegido =m.obtener_datos_productos(self.getname_fromlist)
        self.lbl_forid.setText(str(self.valor_elegido[0]))
        self.input_producto_name.setText(self.valor_elegido[1])
        self.input_categoria_name.setText(self.valor_elegido[2])
        self.input_precio.setText(str(self.valor_elegido[3]))
      
    def borrar_todalatabla(self,):
        self.tabl_widget_productos.clear()            

    def dropdata(self,):
        self.list_productos.blockSignals(True)
        self.list_productos.clear()
        self.list_productos.blockSignals(False)
        #self.list_productos.clearSelection()
        
         #   self.list_productos.clear()

    def buscar_por_nombre(self,):
        self.getinput_name = self.input_find.text()
        self.getall_semejanzas = m.buscar_producto_partedel_nombre(self.getinput_name)
        print(self.getall_semejanzas,"aver papu")
        for x in self.getall_semejanzas:
            QListWidgetItem(x,self.list_productos)

#############################################################################################################











    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Codigo o Nombre de producto"))
        self.label_2.setText(_translate("MainWindow", "Descripcion Producto"))
        self.label_3.setText(_translate("MainWindow", "Categoria"))
        self.label_4.setText(_translate("MainWindow", "Cantidad"))
        self.label_5.setText(_translate("MainWindow", "Precio de Venta"))
        self.label_6.setText(_translate("MainWindow", "Total"))
        self.btn_agregar.setText(_translate("MainWindow", "AÑADIR"))
        self.label_8.setText(_translate("MainWindow", "Cliente"))
        self.label_9.setText(_translate("MainWindow", "DNI"))
        self.label_10.setText(_translate("MainWindow", "Nombre"))
        self.label_11.setText(_translate("MainWindow", "Apellido"))
        self.btn_buscar_dni.setText(_translate("MainWindow", "Buscar"))
        self.label_12.setText(_translate("MainWindow", "Correo"))
        self.chbox_enviarcorreo.setText(_translate("MainWindow", "Enviar factura por correo"))
        self.label_13.setText(_translate("MainWindow", "Carrito"))
        self.label_14.setText(_translate("MainWindow", "Sub total :"))
        self.label_15.setText(_translate("MainWindow", "IVA 18%:"))
        self.label_16.setText(_translate("MainWindow", "Total"))
        self.btn_completar_compra.setText(_translate("MainWindow", "COMPLETAR VENTA"))
        self.btn_lista_productos.setText(_translate("MainWindow", "Buscar"))
        self.btn_limpiar_lista.setText(_translate("MainWindow", "Limpiar"))
        self.label_7.setText(_translate("MainWindow", "id"))
        self.btn_limpiar_tabla.setText(_translate("MainWindow", "Limpiar"))
        self.btn_borrar_item.setText(_translate("MainWindow", "Borrar"))
        self.btn_guardar_cliente.setText(_translate("MainWindow", "Guardar"))
        self.btn_calcular_lprecio.setText(_translate("MainWindow", "Calcular"))
        self.label_17.setText(_translate("MainWindow", "ID"))
        self.label_18.setText(_translate("MainWindow", "Bienvenido"))
        self.label_20.setText(_translate("MainWindow", "id"))
        self.label_21.setText(_translate("MainWindow", "Tipo Empleado"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Menu Principal"))
        self.pushButton_9.setText(_translate("MainWindow", "Buscar"))
        self.label_53.setText(_translate("MainWindow", "Buscar Producto"))
        self.pushButton_10.setText(_translate("MainWindow", "Agregar Producto"))
        self.pushButton_11.setText(_translate("MainWindow", "Agregar Categoria"))
        self.pushButton_12.setText(_translate("MainWindow", "Actualizar"))
        self.cmboxcategoria_productos.setItemText(0, _translate("MainWindow", "Productos"))
        self.cmboxcategoria_productos.setItemText(1, _translate("MainWindow", "Categorias"))
        self.label_22.setText(_translate("MainWindow", "id"))
        self.label_23.setText(_translate("MainWindow", "Tipo Empleado"))
        self.label_19.setText(_translate("MainWindow", "Bienvenido"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_56), _translate("MainWindow", "Inventario"))
        self.label_54.setText(_translate("MainWindow", "Datos"))
        self.label_55.setText(_translate("MainWindow", "Cargo"))
        self.label_56.setText(_translate("MainWindow", "Nombre"))
        self.label_57.setText(_translate("MainWindow", "Celular"))
        self.label_58.setText(_translate("MainWindow", "Correo"))
        self.label_59.setText(_translate("MainWindow", "Edad"))
        self.label_60.setText(_translate("MainWindow", "Apellido"))
        self.label_61.setText(_translate("MainWindow", "Dni"))
        self.label_62.setText(_translate("MainWindow", "Sexo"))
        self.label_63.setText(_translate("MainWindow", "Direccion"))
        self.btn_actualizar_empleado.setText(_translate("MainWindow", "Actualizar"))
        self.label_93.setText(_translate("MainWindow", "Lista de Empleados"))
        self.btn_actualizar_empleado_2.setText(_translate("MainWindow", "Agregar"))
        self.label_24.setText(_translate("MainWindow", "Bienvenido"))
        self.label_25.setText(_translate("MainWindow", "Tipo Empleado"))
        self.label_26.setText(_translate("MainWindow", "id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Usuario"))
        self.pushButton.setText(_translate("MainWindow", "Enviar Vaucher"))
        self.pushButton_2.setText(_translate("MainWindow", "Ver a Detaller"))
        self.checkBox.setText(_translate("MainWindow", "Enviar vaucher al correo Electronio"))
        self.label_27.setText(_translate("MainWindow", "Bienvenido"))
        self.label_28.setText(_translate("MainWindow", "Tipo Empleado"))
        self.label_29.setText(_translate("MainWindow", "id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_55), _translate("MainWindow", "Historial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Menu_venta_principal_()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
